name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  - pip:
    - numpy
    - scipy
    - pandas
    - matplotlib